/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AboutRouteImport } from './routes/about'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VksDashboardRouteImport } from './routes/vks.dashboard'
import { Route as ServicesWebServicesRouteImport } from './routes/services.web-services'
import { Route as ServicesWebRouteImport } from './routes/services.web'
import { Route as ServicesSocialSphereRouteImport } from './routes/services.social-sphere'
import { Route as ServicesMaintenanceSupportRouteImport } from './routes/services.maintenance-support'
import { Route as ServicesMaintenanceRouteImport } from './routes/services.maintenance'
import { Route as ServicesAppDevelopmentRouteImport } from './routes/services.app-development'
import { Route as ServicesAppRouteImport } from './routes/services.app'

const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VksDashboardRoute = VksDashboardRouteImport.update({
  id: '/vks/dashboard',
  path: '/vks/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesWebServicesRoute = ServicesWebServicesRouteImport.update({
  id: '/services/web-services',
  path: '/services/web-services',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesWebRoute = ServicesWebRouteImport.update({
  id: '/services/web',
  path: '/services/web',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSocialSphereRoute = ServicesSocialSphereRouteImport.update({
  id: '/services/social-sphere',
  path: '/services/social-sphere',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesMaintenanceSupportRoute =
  ServicesMaintenanceSupportRouteImport.update({
    id: '/services/maintenance-support',
    path: '/services/maintenance-support',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesMaintenanceRoute = ServicesMaintenanceRouteImport.update({
  id: '/services/maintenance',
  path: '/services/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAppDevelopmentRoute = ServicesAppDevelopmentRouteImport.update({
  id: '/services/app-development',
  path: '/services/app-development',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAppRoute = ServicesAppRouteImport.update({
  id: '/services/app',
  path: '/services/app',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/products': typeof ProductsRoute
  '/terms': typeof TermsRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/services/app': typeof ServicesAppRoute
  '/services/app-development': typeof ServicesAppDevelopmentRoute
  '/services/maintenance': typeof ServicesMaintenanceRoute
  '/services/maintenance-support': typeof ServicesMaintenanceSupportRoute
  '/services/social-sphere': typeof ServicesSocialSphereRoute
  '/services/web': typeof ServicesWebRoute
  '/services/web-services': typeof ServicesWebServicesRoute
  '/vks/dashboard': typeof VksDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/products': typeof ProductsRoute
  '/terms': typeof TermsRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/services/app': typeof ServicesAppRoute
  '/services/app-development': typeof ServicesAppDevelopmentRoute
  '/services/maintenance': typeof ServicesMaintenanceRoute
  '/services/maintenance-support': typeof ServicesMaintenanceSupportRoute
  '/services/social-sphere': typeof ServicesSocialSphereRoute
  '/services/web': typeof ServicesWebRoute
  '/services/web-services': typeof ServicesWebServicesRoute
  '/vks/dashboard': typeof VksDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/products': typeof ProductsRoute
  '/terms': typeof TermsRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/services/app': typeof ServicesAppRoute
  '/services/app-development': typeof ServicesAppDevelopmentRoute
  '/services/maintenance': typeof ServicesMaintenanceRoute
  '/services/maintenance-support': typeof ServicesMaintenanceSupportRoute
  '/services/social-sphere': typeof ServicesSocialSphereRoute
  '/services/web': typeof ServicesWebRoute
  '/services/web-services': typeof ServicesWebServicesRoute
  '/vks/dashboard': typeof VksDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/careers'
    | '/contact'
    | '/privacy'
    | '/privacy-policy'
    | '/products'
    | '/terms'
    | '/terms-of-service'
    | '/services/app'
    | '/services/app-development'
    | '/services/maintenance'
    | '/services/maintenance-support'
    | '/services/social-sphere'
    | '/services/web'
    | '/services/web-services'
    | '/vks/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/careers'
    | '/contact'
    | '/privacy'
    | '/privacy-policy'
    | '/products'
    | '/terms'
    | '/terms-of-service'
    | '/services/app'
    | '/services/app-development'
    | '/services/maintenance'
    | '/services/maintenance-support'
    | '/services/social-sphere'
    | '/services/web'
    | '/services/web-services'
    | '/vks/dashboard'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/about'
    | '/careers'
    | '/contact'
    | '/privacy'
    | '/privacy-policy'
    | '/products'
    | '/terms'
    | '/terms-of-service'
    | '/services/app'
    | '/services/app-development'
    | '/services/maintenance'
    | '/services/maintenance-support'
    | '/services/social-sphere'
    | '/services/web'
    | '/services/web-services'
    | '/vks/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  PrivacyRoute: typeof PrivacyRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ProductsRoute: typeof ProductsRoute
  TermsRoute: typeof TermsRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  ServicesAppRoute: typeof ServicesAppRoute
  ServicesAppDevelopmentRoute: typeof ServicesAppDevelopmentRoute
  ServicesMaintenanceRoute: typeof ServicesMaintenanceRoute
  ServicesMaintenanceSupportRoute: typeof ServicesMaintenanceSupportRoute
  ServicesSocialSphereRoute: typeof ServicesSocialSphereRoute
  ServicesWebRoute: typeof ServicesWebRoute
  ServicesWebServicesRoute: typeof ServicesWebServicesRoute
  VksDashboardRoute: typeof VksDashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vks/dashboard': {
      id: '/vks/dashboard'
      path: '/vks/dashboard'
      fullPath: '/vks/dashboard'
      preLoaderRoute: typeof VksDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/web-services': {
      id: '/services/web-services'
      path: '/services/web-services'
      fullPath: '/services/web-services'
      preLoaderRoute: typeof ServicesWebServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/web': {
      id: '/services/web'
      path: '/services/web'
      fullPath: '/services/web'
      preLoaderRoute: typeof ServicesWebRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/social-sphere': {
      id: '/services/social-sphere'
      path: '/services/social-sphere'
      fullPath: '/services/social-sphere'
      preLoaderRoute: typeof ServicesSocialSphereRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/maintenance-support': {
      id: '/services/maintenance-support'
      path: '/services/maintenance-support'
      fullPath: '/services/maintenance-support'
      preLoaderRoute: typeof ServicesMaintenanceSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/maintenance': {
      id: '/services/maintenance'
      path: '/services/maintenance'
      fullPath: '/services/maintenance'
      preLoaderRoute: typeof ServicesMaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/app-development': {
      id: '/services/app-development'
      path: '/services/app-development'
      fullPath: '/services/app-development'
      preLoaderRoute: typeof ServicesAppDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/app': {
      id: '/services/app'
      path: '/services/app'
      fullPath: '/services/app'
      preLoaderRoute: typeof ServicesAppRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  PrivacyRoute: PrivacyRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ProductsRoute: ProductsRoute,
  TermsRoute: TermsRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  ServicesAppRoute: ServicesAppRoute,
  ServicesAppDevelopmentRoute: ServicesAppDevelopmentRoute,
  ServicesMaintenanceRoute: ServicesMaintenanceRoute,
  ServicesMaintenanceSupportRoute: ServicesMaintenanceSupportRoute,
  ServicesSocialSphereRoute: ServicesSocialSphereRoute,
  ServicesWebRoute: ServicesWebRoute,
  ServicesWebServicesRoute: ServicesWebServicesRoute,
  VksDashboardRoute: VksDashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
